config/routes.rb
Rails.application.routes.draw do

  #ユーザー側のルート
  scope module: :enduser do
    root to: 'homes#top'
    get 'homes/about'
    get 'homes/guide'
    resources :endusers, only: [:show, :edit, :update] do
      resources :relationships, only: [:create, :destroy, ]
    end
    get "following_user/:id" => "relationships#index_following_user", as: "following_user"
    get "follower_user/:id" => "relationships#index_follower_user", as: "follower_user"
    resources :posts, only: [:index, :new, :create, :edit, :update,  :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
     # 検索機能
     get 'search' => 'search#search'
  end

  namespace :enduser do
    resources :pets, only: [:index, :show]
    resources :genres, only: [:show]
    resources :reservations, only: [:index, :show, :create, :update, :destroy]
    resources :inquiries, only: [:new, :create, :show]
  end

  devise_for :endusers, path: :enduser, :controllers => {
    :sessions => 'endusers/sessions', :registrations => 'endusers/registrations', :passwords => 'endusers/passwords'
  }
  # ゲストログイン機能
  devise_scope :enduser do
    post 'endusers/guest_sign_in', to: 'endusers/sessions#new_guest'
  end

  #管理者側のルート
  scope module: :hostuser do
    get 'hostuser_homes/top'
    resources :hostusers, only: [:index]
  end

  namespace :hostuser do
    # devise_for :hostusers, :controllers => {
    #   :sessions => 'hostusers/sessions'
    # }
    resources :genres, only: [:index, :create, :edit, :update]
    resources :pets, only: [:index, :new, :create, :show, :edit, :update]
    resources :reservations, only: [:index]
    resources :inquiries, only: [:index, :update]
  end

  # ゲストログイン機能(管理者側)
  devise_for :hostusers,  path: :hostuser, :controllers => {
    :sessions => 'hostusers/sessions', :registrations => 'hostusers/registrations', :passwords => 'hostusers/passwords'
  }
  devise_scope :hostuser do
    post 'hostusers/guest_sign_in', to: 'hostusers/sessions#new_guest'
  end



end

app/models/hostuser.rb
class Hostuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'hostuserguest@example.com') do |hostuser|
      hostuser.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  attachment :animal_image

  belongs_to :genre

  enum age:{ blank: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10,
            eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20}, _prefix: true
  enum sex:{ blank: 0, male: 1, female: 2 }, _prefix: true
  enum size: { blank: 0, small: 1, medium: 2, large: 3,cat: 4 }, _prefix: true
  enum vaccine_status: {  blank: 0, before: 1, after: 2}, _prefix: true
  enum castration_status: { blank: 0, before: 1, after: 2 }
  enum single_status: { blank: 0, ok: 1, ng: 2 }, _prefix: true
  enum older_status: { blank: 0, ok: 1, ng: 2 }, _prefix: true
  enum pet_status: { blank: 0, invite: 1, stop: 2, decide: 3 }, _prefix: true
  enum prefectures:{
      blank: 0,
      hokkaido:1,aomori:2,iwate:3,miyagi:4,akita:5,yamagata:6,fukushima:7,
      ibaraki:8,tochigi:9,gunnma:10,saitama:11,chiba:12,tokyo:13,kanagawa:14,
      niigata:15,toyama:16,ishikawa:17,fukui:18,yamanashi:19,nagano:20,
      gifu:21,shizuoka:22,aichi:23,mie:24,
      shiga:25,kyoto:26,osaka:27,hyogo:28,nara:29,wakayama:30,
      tottori:31,shimane:32,okayama:33,hiroshima:34,yamaguchi:35,
      tokushima:36,kagawa:37,ehime:38,kochi:39,
      fukuoka:40,saga:41,nagasaki:42,kumamoto:43,oita:44,miyazaki:45,kagoshima:46,okinawa:47
    }, _prefix: true

  validates :name, presence: true
  validates :kind, presence: true
  validates :detail, presence: true

  validates :age, inclusion: {in: Pet.ages.keys[1..-1] }
  validates :sex, inclusion: {in: Pet.sexes.keys[1..-1] }
  validates :size, inclusion: {in: Pet.sizes.keys[1..-1] }
  validates :vaccine_status, inclusion: {in: Pet.vaccine_statuses.keys[1..-1] }
  validates :castration_status, inclusion: {in: Pet.castration_statuses.keys[1..-1] }
  validates :single_status, inclusion: {in: Pet.single_statuses.keys[1..-1] }
  validates :older_status, inclusion: {in: Pet.older_statuses.keys[1..-1] }
  validates :prefectures, inclusion: {in: Pet.prefectures.keys[1..-1] }
  validates :pet_status, inclusion: {in: Pet.pet_statuses.keys[1..-1] }

end

app/controllers/enduser/pets_controller.rb
class Enduser::PetsController < Enduser::Base
  before_action :authenticate_enduser!, only: [:show]

  def index
    @pets = Pet.where(pet_status: "invite" )
    @genres = Genre.where(valid_flag: false )
  end

  def show
    @pet = Pet.find(params[:id])
  end

end

app/controllers/hostuser/base.rb
class Hostuser::Base < ApplicationController
  layout 'hostuser'
end

app/controllers/hostuser/genres_controller.rb
class Hostuser::GenresController < Hostuser::Base
  before_action :authenticate_hostuser!

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを追加しました"
      redirect_to hostuser_genres_path
    else
      @genres = Genre.all.page(params[:page]).per(10)
      flash.now[:alert] = '入力に不備があります'
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンルを変更しました"
      redirect_to hostuser_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :valid_flag)
  end

end

app/controllers/hostuser/hostuser_homes_controller.rb
class Hostuser::HostuserHomesController < Hostuser::Base
  before_action :authenticate_hostuser!

  def top
    @reservations = Reservation.all
  end
end

app/controllers/hostuser/hostusers_controller.rb
class Hostuser::HostusersController < Hostuser::Base
  before_action :authenticate_hostuser!

  def index
    @endusers = Enduser.all
  end

end

app/controllers/hostuser/inquiries_controller.rb
class Hostuser::InquiriesController < Hostuser::Base
  before_action :authenticate_hostuser!

  def index
    @inquiries = Inquiry.all.order("id DESC")
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update(inquiry_params)
      flash[:notice] = "返信済みに更新しました"
      redirect_back fallback_location:  @inquiry
    else
      @inquiries = Inquiry.all
      render :index
    end
  end

  def inquiry_params
    params.require(:inquiry).permit(:email, :message, :name, :reply_status)
  end

end

app/controllers/hostuser/pets_controller.rb
class Hostuser::PetsController < Hostuser::Base
  before_action :authenticate_hostuser!

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
    @genres = Genre.all
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      flash[:notice] = "登録が出来ました"
      redirect_to hostuser_pet_path(@pet.id)
    else
      @genres = Genre.all
      render :new
    end
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
    @genres = Genre.all
  end

  def update
    @pet = Pet.find(params[:id])

    if @pet.update(pet_params)
      flash[:notice] = "商品情報を更新しました"
      redirect_to hostuser_pet_path(@pet.id)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:genre_id, :name, :kind, :age, :sex, :size, :animal_image, :vaccine_status, :castration_status,
                                :single_status, :older_status, :pet_status, :prefectures, :detail)
  end

end

app/controllers/hostuser/reservations_controller.rb
class Hostuser::ReservationsController < Hostuser::Base
  before_action :authenticate_hostuser!

  def index
    @reservations = Reservation.all
  end

end

app/controllers/hostusers/confirmations_controller.rb
# frozen_string_literal: true

class Hostusers::ConfirmationsController < Devise::ConfirmationsController
  layout 'hostuser'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/hostusers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Hostusers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 'hostuser'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/hostusers/passwords_controller.rb
# frozen_string_literal: true

class Hostusers::PasswordsController < Devise::PasswordsController
  layout 'hostuser'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/hostusers/registrations_controller.rb
# frozen_string_literal: true

class Hostusers::RegistrationsController < Devise::RegistrationsController
  layout 'hostuser'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/hostusers/sessions_controller.rb
# frozen_string_literal: true

class Hostusers::SessionsController < Devise::SessionsController
  layout 'hostuser'
  
  # ゲストログイン機能
  def new_guest
    @hostuser = Hostuser.guest
    sign_in @hostuser
    redirect_to hostuser_homes_top_path, notice: 'ゲストユーザーとしてログインしました。(管理者側)'
  end
  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/hostusers/unlocks_controller.rb
# frozen_string_literal: true

class Hostusers::UnlocksController < Devise::UnlocksController
  layout 'hostuser'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/hostuser/inquiries_helper.rb
module Hostuser::InquiriesHelper
end

app/helpers/hostusers_helper.rb
module HostusersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/hostuser/pets/edit.html.erb
<div class="top-border"><%= image_tag('border.png', :size =>'1200x5') %></div>
<div class="top-img"><%= image_tag('concept2.png', :size =>'1200x150') %></div>

<div class="link_bar">
  <%= link_to "top", hostuser_homes_top_path %>
  <span>>></span>
  <%= link_to "ペット一覧", hostuser_pets_path %>
  <span>>></span>
  <%= link_to "ペット詳細", hostuser_pet_path(@pet) %>
  <span>>></span>
  <%= link_to "ペット編集", edit_hostuser_pet_path(@pet) ,data: {"turbolinks" => false} %>
</div>

<h2>ペットを編集する</h2>
<div class="hostuser-pet-edit">
   <%= form_with model: @pet, url: hostuser_pet_path, method: :PATCH, local: true do |f| %>
    <!--エラー文-->
    <% if @pet.errors.any? %>
     <div class=“error_explanation”>
     <h5 class="text-danger"><%= @pet.errors.count %>件のエラーが発生しました。</h5>
     <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li class="text-danger">●<%= message %></li>
      <% end %>
        </ul>
      </div>
    <% end %>
    <!--ペット更新フォーム-->
    <div class="row">
      <div class="field col-xl-4 col-md-3 col-3">
        <%= attachment_image_tag @pet, :animal_image, fallback: 'no-image.jpg', size: '300x200', onChange: "$('.img_field').change()", class: 'center-block img_prev'%>
        <%= f.attachment_field :animal_image, class: 'img_field' %><br>
      </div>
      <div class="col-xl-5 col-md-3">
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :ジャンル, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "-- 入力してください --"}, {class: "col-xl-7 col-md-5 col-2"}) %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :名前, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.text_field :name, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12 item">
          <%= f.label :種類, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.text_area :kind, rows: 1, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :年齢, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :age, Pet.ages_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :性別, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :sex, Pet.sexes_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :サイズ, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :size, Pet.sizes_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :ワクチン, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :vaccine_status, Pet.vaccine_statuses_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :去勢・避妊, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :castration_status, Pet.castration_statuses_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :単身者の応募, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :single_status, Pet.single_statuses_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :高齢者の応募, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :older_status, Pet.single_statuses_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :都道府県, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :pet_status, Pet.pet_statuses_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :募集状況, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.select :prefectures, Pet.prefectures_i18n.invert, {}, class: "col-xl-7 col-md-5 col-2" %>
        </div>
        <div class="field col-xl-12 col-md-12 col-12">
          <%= f.label :備考欄, class: "col-xl-4 col-md-5 col-1" %>
          <%= f.text_field :detail , class: "col-xl-7 col-md-5 col-2" %>
        </div>
      </div>
      <div class="col-xl-2 col-md-3">
        <div class="hostuser-pet-edit-btn actions col-xl-12 col-md-4">
          <%= f.submit "更新する", class: "btn btn-outline-dark" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/hostuser/pets/index.html.erb
<div class="top-border"><%= image_tag('border.png', :size =>'1200x5') %></div>
<div class="top-img"><%= image_tag('concept2.png', :size =>'1200x150') %></div>

<div class="link_bar">
  <%= link_to "top", hostuser_homes_top_path %>
  <span>>></span>
  <%= link_to "ペット一覧", hostuser_pets_path %>
</div>


<div class="hostuser-pet-index">
  <h2>登録ペット一覧</h2>
  <table class="table table-borderless table-borderless-pet-index-media-big428">
    <div class="hostuser-pet-new">
      <%= link_to "" , new_hostuser_pet_path, data: {"turbolinks" => false}, class: "fa fa-plus-square-o" %>
    </div>
    <thead>
      <tr>
        <th>id</th>
        <th>genre</th>
        <th>kind</th>
        <th>name</th>
        <th>image</th>
        <td>sex</td>
        <th>pet_status</th>
        <th><i class="fas fa-paw"></i></th>
        <th><i class="fas fa-wrench"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.id %></td>
          <td><%= pet.genre.name %></td>
          <td><%= pet.kind %></td>
          <td><%= pet.name %></td>
          <td><%= attachment_image_tag pet, :animal_image, fallback: 'no-image.jpg', size: '40x40'%></td>
          <td><%= pet.sex_i18n %></td>
          <td><%= pet.pet_status_i18n %></td>
          <td><%= link_to "詳細", hostuser_pet_path(pet), class: "btn btn-outline-dark" %></td>
          <td><%= link_to "編集", edit_hostuser_pet_path(pet) ,data: {"turbolinks" => false}, class: "btn btn-outline-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!--メディア-->
  <table class="table table-borderless table-borderless-pet-index-media-small428">
    <!--<div class="hostuser-pet-new">-->
    <!--  <%#= link_to "" , new_hostuser_pet_path, data: {"turbolinks" => false}, class: "fa fa-plus-square-o" %>-->
    <!--</div>-->
    <thead>
      <tr>
        <th>genre</th>
        <th>name</th>
        <th>pet_status</th>
        <th><i class="fas fa-paw"></i></th>
        <th><i class="fas fa-wrench"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @pets.each do |pet| %>
        <tr>
          <td><%= pet.genre.name %></td>
          <td><%= pet.name %></td>
          <td><%= pet.pet_status_i18n %></td>
          <td><%= link_to "詳細", hostuser_pet_path(pet), class: "btn btn-outline-dark" %></td>
          <td><%= link_to "編集", edit_hostuser_pet_path(pet) ,data: {"turbolinks" => false}, class: "btn btn-outline-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/hostuser/pets/show.html.erb
<div class="top-border"><%= image_tag('border.png', :size =>'1200x5') %></div>
<div class="top-img"><%= image_tag('concept2.png', :size =>'1200x150') %></div>

<div class="link_bar">
  <%= link_to "top", hostuser_homes_top_path %>
  <span>>></span>
  <%= link_to "ペット一覧", hostuser_pets_path %>
  <span>>></span>
  <%= link_to "ペット詳細", hostuser_pet_path %>
</div>

<div class="hostuser-pet-show hostuser-pet-show-media-big428">
  <h2><%= @pet.name %></h2>
  <div class="row">
    <div class="col-xl-7 col-xl-offset-1 col-md-4 ">
      <%= attachment_image_tag @pet, :animal_image, fallback: 'no-image.jpg', size: '600x400' %>
    </div>
    <div class="col-xl-2 col-md-1">
        <ul>
          <li>ジャンル：</li>
          <li>名前：</li>
          <li>性別：</li>
          <li>年齢</li>
          <li>種類：</li>
          <li>サイズ：</li>
          <li>都道府県</li>
          <li>去勢・避妊</li>
          <li>単身者応募：</li>
          <li>高齢者応募：</li>
          <li>備考:</li>
          <li>現在の募集状況：</li>
        </ul>
      </div>
      <div class="col-xl-2 col-md-2">
        <ul>
          <li><%= @pet.genre.name %></li>
          <li><%= @pet.name %></li>
          <li><%= @pet.sex_i18n %></li>
          <li><%= @pet.age_i18n%></li>
          <li><%= @pet.kind %></li>
          <li><%= @pet.size_i18n %></li>
          <li><%= @pet.prefectures_i18n %></li>
          <li><%= @pet.castration_status_i18n %></li>
          <li><%= @pet.single_status_i18n %></li>
          <li><%= @pet.older_status_i18n %></li>
          <li><%= @pet.detail %></li>
          <li><%= @pet.pet_status_i18n %></li>
        </ul>
      </div>
    <div class="pet-show-btn">
      <%= link_to "編集", edit_hostuser_pet_path(@pet) ,data: {"turbolinks" => false}, class: "btn btn-outline-dark"%>
    </div>
  </div>
</div>
<!--メディア-->
<div class="hostuser-pet-show-media-small428">
  <h2><%= @pet.name %></h2>
  <div class="hostuser-pet-show-media-small428-img">
    <%= attachment_image_tag @pet, :animal_image, fallback: 'no-image.jpg', size: '600x400' %>
  </div>
  <div class="row">
    <div class="col-4">
      <ul>
        <li>ジャンル：</li>
        <li>名前：</li>
        <li>性別：</li>
        <li>年齢</li>
        <li>種類：</li>
        <li>サイズ：</li>
        <li>都道府県</li>
        <li>去勢・避妊</li>
        <li>単身者応募：</li>
        <li>高齢者応募：</li>
        <li>備考:</li>
        <li>現在の募集状況：</li>
      </ul>
    </div>
    <div class="col-4">
      <ul>
        <li><%= @pet.genre.name %></li>
        <li><%= @pet.name %></li>
        <li><%= @pet.sex_i18n %></li>
        <li><%= @pet.age_i18n%></li>
        <li><%= @pet.kind %></li>
        <li><%= @pet.size_i18n %></li>
        <li><%= @pet.prefectures_i18n %></li>
        <li><%= @pet.castration_status_i18n %></li>
        <li><%= @pet.single_status_i18n %></li>
        <li><%= @pet.older_status_i18n %></li>
        <li><%= @pet.detail %></li>
        <li><%= @pet.pet_status_i18n %></li>
      </ul>
    </div>
    <div class="pet-show-btn col-1">
      <%= link_to "編集", edit_hostuser_pet_path(@pet) ,data: {"turbolinks" => false}, class: "btn btn-outline-dark"%>
    </div>
  </div>
</div>